audiotext/urls.py
from django.urls import path, include
from . import views

app_name = 'audiotext'
urlpatterns = [
    path('create_audio/', views.create_audio, name='create_audio'),
]

carnews/urls.py
from django.urls import path, include
from . import views

app_name = 'carnews'
urlpatterns = [
    path('news/', views.news, name='news'),
]

file_converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pdf2word_conv.urls')),
    path('', include('audiotext.urls')),
    path('', include('carnews.urls')),
]

pdf2word_conv/urls.py
from django.urls import path, include
from . import views

app_name = 'pdf2word_conv'
urlpatterns = [
    path('', views.index, name='index'),
    path('pdf_converter/', views.pdf_converter, name='pdf_converter'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

audiotext/models.py
from django.db import models
from django.core.files import File

# Create your models here.
class Uploaded_File(models.Model):
    file = models.FileField(upload_to='')

    def __str__(self):
        return str(self.file)

carnews/models.py
from django.db import models

# Create your models here.

pdf2word_conv/models.py
from django.db import models
from django.core.files import File


# all data saves in database. Each file has an id and path
class Uploaded_File(models.Model):
    id = models.IntegerField(primary_key=True)
    file = models.FileField(upload_to='')

    def __str__(self):
        return str(self.file)

audiotext/forms.py
from django import forms


class VoiceTextForm(forms.Form):
    text = forms.CharField()
    language_choices = (("en", "English"),("fr", "French"),("zh-CN", "Mandarin (China Mainland)"),)
    language = forms.ChoiceField(choices = language_choices)

pdf2word_conv/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField(label='Select a PDF file',)

audiotext/views.py
from django.shortcuts import render
from .forms import VoiceTextForm
from audiotext.audiobuilder import *
from django.http import FileResponse


# Create audio file from text
def create_audio(request):
    if request.method != "POST":

        # Display blank registration form.
        form = VoiceTextForm()
    else:
        # Process completed form.
        form = VoiceTextForm(request.POST)

        if form.is_valid():
            text = form.cleaned_data['text']

            # Define text language
            language = form.cleaned_data['language']

            # Initialize audio builder class
            audiobuilder = AudioBuilder()

            # Call build audio method
            audio_file = audiobuilder.build_audio(text, language)
            response = FileResponse(
                open(f'{audio_file}', 'rb'), as_attachment=True)
            return response

    return render(request, 'audiotext/create_audio.html', {'form': form})

carnews/views.py
from django.shortcuts import render
from carnews.news import *
from carnews.article import *

# Show only official car news from Motor1.com


def news(request):

    # News storage
    all_news = []

    # Initialize and call news parser
    parser = News_parser()
    parsed_news = parser.parse_news()
    for key, value in parsed_news.items():
        print(value.keys())

    for article in parsed_news:

        # Update storage with articles
        all_news.append(Article(parsed_news[article]))

    context = {'parsed_news': parsed_news, 'all_news': all_news}

    return render(request, 'carnews/news.html', context)
# Create your views here.

pdf2word_conv/views.py
from django.shortcuts import render
from pdf2word_conv.pdf_converter import *
from .forms import UploadFileForm
from .models import Uploaded_File
from django.http import FileResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    return render(request, 'pdf2word_conv/index.html')

# Only logged in user can use this application


@login_required
# This method takes a .PDF file from user input, saves it and converts to
# the .DOCX file
def pdf_converter(request):

    # Check type of request
    if request.method != 'POST':
        form = UploadFileForm()
    else:
        form = UploadFileForm(request.POST, request.FILES)

        # Check form valid
        if form.is_valid():
            uploaded_file = Uploaded_File(file=request.FILES['file'])
            uploaded_file.save()

            # Changing a file name for database
            changed_file_name = Uploaded_File.objects.get(
                file=f"{request.FILES['file'].name.replace(' ','_')}")

            # Initialize FileConverter class to pass the .PDF file
            converter = FileConverter()
            converted_file = converter.create_file(
                changed_file_name.file.path, changed_file_name)

            # Check file readiness
            # If file wasn't generated, raise an error
            # This application work with files without images inside .PDF files
            # only
            if converted_file:
                response = FileResponse(
                    open(
                        f'{converted_file}',
                        'rb'),
                    as_attachment=True)
                return response
            else:
                messages.info(request, ".pdf files without images only!")

    return render(request, 'pdf2word_conv/pdf_converter.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import get_user_model
from users.check_request_data import *


def register(request):
    if request.method != 'POST':

        # Display blank registration form.
        form = UserCreationForm()
    else:

        # Process completed form.
        form = UserCreationForm(data=request.POST)

        # Check registration data. If invalid returns message.
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        check_data = Check_Data()

        if check_data.exist_user(username):
            messages.info(request, 'This user already exists.')
        elif check_data.match_passwords(password1, password2) != True:
            messages.info(request, "Passwords doesn't match. Try again.")
        else:
            if form.is_valid():
                new_user = form.save()

                # Log the user in and then redirect to home page.
                login(request, new_user)
                return redirect('pdf2word_conv:index')
            else:

                # Raise password error
                messages.info(
                    request, 'Your password is too simple. Try another.')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

audiotext/templates/audiotext/create.html
{% extends 'pdf2word_conv/base.html' %}

{% block content %}

<div class="mt-5">
	<h2>VOICE TEXT</h2>

		<form method="post">
		{% csrf_token %}
			<div class="input-group cover-container d-flex w-75 h-25 p-3 mx-auto">
				<textarea placeholder="Enter text" class="form-control" id="id_text" type="text" name="text" rows="10" required></textarea>
			</div>
			<div class="cover-container d-flex w-25 h-25 p-3 mx-auto flex-column">
				<div id="emailHelp" class="form-text mb-3">Choose language</div>
				<select required class="form-select" for="id_language" name="language" aria-label="Default select example">
				  <option value="en">English</option>
				  <option value="fr">French</option>
				  <option value="zh-CN">Mandarin (China Mainland)</option>
				  <option value="3">Portuguese</option>
				  <option value="3">Spanish</option>
				</select>

			<button type="submit" class="btn btn-primary mt-2">Create audio</button>
		</div>
		</form>
</div>

		

{% endblock content %}

audiotext/templates/audiotext/create_audio.html
{% extends 'pdf2word_conv/base.html' %}

{% block content %}

<div class="mt-5">
	<h2>VOICE TEXT</h2>

		<form method="post">
		{% csrf_token %}
			<div class="input-group cover-container d-flex w-75 h-25 p-3 mx-auto">
				<textarea placeholder="Enter text" class="form-control" id="id_text" type="text" name="text" rows="10" required></textarea>
			</div>
			<div class="cover-container d-flex w-25 h-25 p-3 mx-auto flex-column">
				<div id="emailHelp" class="form-text mb-3">Choose language</div>
				<select required class="form-select" for="id_language" name="language" aria-label="Default select example">
				  <option value="en">English</option>
				  <option value="fr">French</option>
				  <option value="zh-CN">Mandarin (China Mainland)</option>
				  <option value="3">Portuguese</option>
				  <option value="3">Spanish</option>
				</select>

			<button type="submit" class="btn btn-primary mt-2">Create audio</button>
		</div>
		</form>
</div>

		

{% endblock content %}

carnews/templates/carnews/news.html
{% extends 'pdf2word_conv/base.html' %}

{% block content %}

<div class="container mt-5">

  <div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 g-3">

            {% for article in all_news %}

            <div class="col col-lg-4">
              <div class="card text-white bg-secondary" style="height: 440px;">
                <img src="{{ article.image }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{ article.title }}</h5>
                  <div style="height: 75px;">
                    <p class="card-text">{{ article.description }}</p>
                  </div>
                  <div class="d-grid gap-2">
                    <a href="{{ article.link }}" class="btn btn-primary" type="button">Read full</a>
                  </div>
                </div>
              </div>
            </div>

            {% endfor %}
  </div>

</div>


<!--     <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div> -->


{% endblock content %}

pdf2word_conv/templates/pdf2word_conv/base.html
{% load static %}
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'pdf2word_conv/custom.css' %}">

    <title>Application holder</title>
  </head>

  <body class="d-flex h-100 text-center" style="background-color: #DFF6FF;">
    
    <div class="cover-container d-flex w-75 h-75 p-3 mx-auto flex-column">
      <header class="mb-auto">
          <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #06283D;">
            <div class="container-fluid">
              <div class="d-flex justify-content-center">
                <a class="navbar-brand" href="{% url 'pdf2word_conv:index' %}">TEST APPLICATIONS</a>
              </div>  
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'pdf2word_conv:index' %}">Home</a>
                  </li>
                  <div class="position-absolute top-50 start-50 translate-middle">
                    <div class="form-check form-switch  text-white-50">
                      <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" disabled>
                      <label class="form-check-label" for="flexSwitchCheckDefault">Translate news</label>
                    </div>
                  </div>

                </ul>
                {% if user.is_authenticated %}
                  <a href="{% url 'users:logout' %}" class="btn btn-danger btn-lg active" role="button" aria-pressed="true">Logout</a>
                {% else %}
                  <a class="btn btn-primary btn-lg active me-3" aria-current="page" href="{% url 'users:login' %}">Log in</a>
                  <a class="btn btn-info btn-lg active" aria-current="page" href="{% url 'users:register' %}">Register</a>

                {% endif %}
              </div>
            </div>
          </nav>

      </header>
      
      <main class="mt-5">
        {% block content %}
        {% endblock content %}
      </main>

<!--       <footer class="text muted py-5 text-white-50">

        <div class="container">
          <p class="float-end mb-1">
            <a href="#">Back to top</a>
          </p>
          <p>Made by Osipov.k using Django, Bootstrap 5 and pip libraries</p>
        </div>

      </footer> -->

    </div>

  </body>

</html>
      
  

pdf2word_conv/templates/pdf2word_conv/conv_to_word.html
{% extends 'pdf2word_conv/base.html' %}


{% block content %}
	<div class="position-absolute top-50 start-50 translate-middle">
			<h2>PDF TO DOCX CONVERTER</h2>

		<form enctype="multipart/form-data" method="post">
			{% csrf_token %}
					<p>
						<label class="form-label" for="id_file">Select PDF file</label>
						<input  accept="application/pdf" class="form-control" id="id_file" type="file" name="file" required="">
						<div id="emailHelp" class="form-text">PDF files without images only.</div>
					</p>
				<button type="submit" class="btn btn-primary mt-2">Send file</button>
		</form>
		
		{% if messages %}
			<ul class="messages">
		    {% for message in messages %}
			    <li
			    {% if message.tags %} class="{{ message.tags }} text-danger p-3"{% endif %}>{{ message }}
				</li>
		    {% endfor %}
			</ul>
		{% endif %}
	</div>

{% endblock content %}

pdf2word_conv/templates/pdf2word_conv/index.html
{% extends 'pdf2word_conv/base.html' %}

{% block content %}

  <div class="position-absolute top-50 start-50 translate-middle">
    <p class="h2 mb-5">Make actions with files and text.</p>

    <div>
    	<a class="btn btn-primary btn-lg p-3 mb-3"
    	href="{% url 'pdf2word_conv:pdf_converter' %}" 
    	role="button" style="width: 500px;">Convert PDF to DOCX</a>
    </div>

    <div>
      <a class="btn btn-primary btn-lg p-3 mb-3"
      href="{% url 'audiotext:create_audio' %}" 
      role="button" style="width: 500px;">Voice text</a>
    </div>


    <div>
      <a class="btn btn-primary btn-lg p-3 mb-3"
      href="{% url 'carnews:news' %}" 
      role="button" style="width: 500px;">Car news</a>
    </div>
  </div>

{% endblock content %}

pdf2word_conv/templates/pdf2word_conv/pdf_converter.html
{% extends 'pdf2word_conv/base.html' %}


{% block content %}

	<div class="position-absolute top-50 start-50 translate-middle">
			<h2>PDF TO DOCX CONVERTER</h2>

		<form enctype="multipart/form-data" method="post">
			{% csrf_token %}
					<p>
						<label class="form-label" for="id_file">Select PDF file</label>
						<input  accept="application/pdf" class="form-control" id="id_file" type="file" name="file" required="">
						<div id="emailHelp" class="form-text">PDF files without images only.</div>
					</p>
				<button type="submit" class="btn btn-primary mt-2">Send file</button>
		</form>
		
		{% if messages %}
			<ul class="messages">
		    {% for message in messages %}
			    <li
			    {% if message.tags %} class="{{ message.tags }} text-danger p-3"{% endif %}>{{ message }}
				</li>
		    {% endfor %}
			</ul>
		{% endif %}
	</div>

{% endblock content %}